#!/usr/bin/env bash

USERNAME=voidxnull
IMAGE=zeropool-substrate-node

VERSION=`cat VERSION`

docker build -t $USERNAME/$IMAGE:latest . && \
docker tag $USERNAME/$IMAGE:latest $USERNAME/$IMAGE:$VERSION && \
docker push $USERNAME/$IMAGE:latest && \
docker push $USERNAME/$IMAGE:$VERSION
